"""add_territory_name_to_documents

Revision ID: 52051817e8c1
Revises: 26e9227ca00f
Create Date: 2026-01-13 14:55:06.354130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52051817e8c1'
down_revision = '26e9227ca00f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('territory_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_documents_territory_name'), 'documents', ['territory_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_territory_name'), table_name='documents')
    op.drop_column('documents', 'territory_name')
    # ### end Alembic commands ###
