"""add_territorial_codes_to_authority_profiles

Revision ID: 26e9227ca00f
Revises: ea6f6e1b0f65
Create Date: 2026-01-10 10:56:45.607208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26e9227ca00f'
down_revision = 'ea6f6e1b0f65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('secret_hash', sa.String(length=255), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('client_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_access_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('access_token_hash', sa.String(length=255), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.String(length=500), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_auth_codes',
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('oauth_refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('access_token_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['access_token_id'], ['oauth_access_tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_refresh_tokens_access_token_id'), 'oauth_refresh_tokens', ['access_token_id'], unique=False)
    op.add_column('authority_profiles', sa.Column('codigo_municipio', sa.String(length=10), nullable=True))
    op.add_column('authority_profiles', sa.Column('codigo_departamento', sa.String(length=10), nullable=True))
    op.add_column('authority_profiles', sa.Column('codigo_region', sa.String(length=10), nullable=True))
    op.add_column('authority_profiles', sa.Column('cedula', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_authority_profiles_cedula'), 'authority_profiles', ['cedula'], unique=False)
    op.create_index(op.f('ix_authority_profiles_codigo_departamento'), 'authority_profiles', ['codigo_departamento'], unique=False)
    op.create_index(op.f('ix_authority_profiles_codigo_municipio'), 'authority_profiles', ['codigo_municipio'], unique=False)
    op.create_index(op.f('ix_authority_profiles_codigo_region'), 'authority_profiles', ['codigo_region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authority_profiles_codigo_region'), table_name='authority_profiles')
    op.drop_index(op.f('ix_authority_profiles_codigo_municipio'), table_name='authority_profiles')
    op.drop_index(op.f('ix_authority_profiles_codigo_departamento'), table_name='authority_profiles')
    op.drop_index(op.f('ix_authority_profiles_cedula'), table_name='authority_profiles')
    op.drop_column('authority_profiles', 'cedula')
    op.drop_column('authority_profiles', 'codigo_region')
    op.drop_column('authority_profiles', 'codigo_departamento')
    op.drop_column('authority_profiles', 'codigo_municipio')
    op.drop_index(op.f('ix_oauth_refresh_tokens_access_token_id'), table_name='oauth_refresh_tokens')
    op.drop_table('oauth_refresh_tokens')
    op.drop_table('oauth_auth_codes')
    op.drop_table('oauth_access_tokens')
    op.drop_table('oauth_clients')
    # ### end Alembic commands ###
